'use strict';

const path = require('path');
const fs = require('fs');

/**
 * Converts a model name string into a safe file name.
 * @param {string} name - Human-readable model name.
 * @returns {string} Filesystem-safe file name without extension.
 */
function toFileName(name) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Converts a comma-separated string into a Markdown bullet list.
 * @param {string} value - Comma-separated string.
 * @returns {string} Markdown list or empty string.
 */
function toBulletList(value) {
  if (!value || !value.trim()) return '';
  return value
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean)
    .map((item) => `- ${item}`)
    .join('\n');
}

/**
 * Generates the full Markdown content for an AI model configuration.
 * @param {Object} answers - Answers keyed by question id.
 * @returns {string} Complete Markdown string.
 */
function generateMarkdown(answers) {
  const {
    modelName,
    modelDescription,
    primaryUseCase,
    tone,
    language,
    expertiseAreas,
    constraints,
    askClarifyingQuestions,
    responseFormat,
    additionalInstructions,
  } = answers;

  const createdAt = new Date().toISOString().split('T')[0];
  const expertiseList = toBulletList(expertiseAreas);
  const constraintList = toBulletList(constraints);
  const clarifying = askClarifyingQuestions === true || askClarifyingQuestions === 'true' || askClarifyingQuestions === 'yes' ? 'Yes' : 'No';

  const lines = [
    `# ${modelName}`,
    '',
    `> **Description:** ${modelDescription}`,
    `> **Created:** ${createdAt}`,
    '',
    '---',
    '',
    '## System Prompt',
    '',
    `You are ${modelName}, an AI assistant. ${modelDescription}`,
    '',
    '## Configuration',
    '',
    `| Setting | Value |`,
    `|---------|-------|`,
    `| Primary Use Case | ${primaryUseCase} |`,
    `| Tone | ${tone} |`,
    `| Language | ${language} |`,
    `| Ask Clarifying Questions | ${clarifying} |`,
    `| Response Format | ${responseFormat} |`,
    '',
  ];

  if (expertiseList) {
    lines.push('## Expertise Areas', '', expertiseList, '');
  }

  if (constraintList) {
    lines.push('## Constraints', '', constraintList, '');
  }

  if (additionalInstructions && additionalInstructions.trim()) {
    lines.push('## Additional Instructions', '', additionalInstructions.trim(), '');
  }

  lines.push(
    '---',
    '',
    '## Behaviour Guidelines',
    '',
    `- Respond exclusively in **${language}** unless the user switches language.`,
    `- Maintain a **${tone.toLowerCase()}** tone in all responses.`,
    `- Format detailed answers using **${responseFormat.toLowerCase()}**.`,
    `- ${clarifying === 'Yes' ? 'When a request is ambiguous, ask one focused clarifying question before answering.' : 'Do not ask clarifying questions; make reasonable assumptions and answer directly.'}`,
  );

  if (constraintList) {
    lines.push('- Avoid discussing: ' + (constraints || '').split(',').map((s) => s.trim()).filter(Boolean).join(', ') + '.');
  }

  lines.push(
    '',
    '---',
    '',
    '## Open Web UI Import Instructions',
    '',
    '1. Open **Open Web UI** in your browser.',
    '2. Navigate to **Settings → Models** (or **Workspace → Models**).',
    '3. Click **"New Model"** or **"Import"**.',
    '4. Paste the contents of the **System Prompt** section above into the **System Prompt** field.',
    '5. Fill in the model name, description, and any other fields from the **Configuration** table.',
    '6. Save the model configuration.',
    '',
    '_This file was generated by the tampermonkey md-config-service._',
  );

  return lines.join('\n');
}

/**
 * Writes a Markdown configuration file to the output directory.
 * @param {Object} answers - Answers keyed by question id.
 * @param {string} outputDir - Directory where the file should be written.
 * @returns {string} Absolute path of the written file.
 */
function writeConfigFile(answers, outputDir) {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const fileName = toFileName(answers.modelName) + '.md';
  const filePath = path.join(outputDir, fileName);
  const content = generateMarkdown(answers);

  fs.writeFileSync(filePath, content, 'utf8');
  return filePath;
}

module.exports = { generateMarkdown, writeConfigFile, toFileName, toBulletList };
